# SPDX-License-Identifier: GPL-3.0-or-later

this_dir := $(dir $(lastword $(MAKEFILE_LIST)))

note-src := $(this_dir)/index.ja.tex $(wildcard $(this_dir)/*.tex)
note-y   := $(this_dir)/$(objtree)/note.pdf

$(note-y): $(note-src)
	mkdir -p $(@D)
	$(lualatex) --output-directory=$(@D) --jobname=$(basename $(@F)) $<
